# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: modelsearch
  version: '1.2'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/modelsearch-${{ version }}.tar.gz
  sha256: c150eb8bc0317fd5e656eb54f3b6809da313588a9998796a4e59a1cfed273ee7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80,<81
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2
    - django-tasks >=0.7,<0.12
    - elasticsearch
    - opensearch-py
tests:
  - python:
      imports:
        - modelsearch
      pip_check: true
      python_version:
        - ${{ python_min }}.*

about:
  summary: A library for indexing Django models with Elasicsearch, OpenSearch or database and searching them with the Django ORM.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/wagtail/django-modelsearch
  repository: https://github.com/wagtail/django-modelsearch

extra:
  recipe-maintainers:
    - darynwhite
    - rxm7706
